tap "adoptopenjdk/openjdk"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "mongodb/brew"

brew "antigen"
brew "diff-so-fancy"
brew "direnv"
brew "fzf"
brew "git-extras"
brew "gnupg"
brew "go"
brew "graphviz"
brew "heroku/brew/heroku"
brew "htop"
brew "httpie"
brew "jenv"
brew "jmeter"
brew "jq"
brew "mas"
brew "mongodb-community@4.2", restart_service: true
brew "pinentry-mac"
brew "postgresql", restart_service: true
brew "pyenv"

cask "1password"
cask "1password-cli"
cask "adobe-acrobat-reader"
cask "alfred"
cask "appcleaner"
cask "balsamiq-wireframes"
cask "batteries"
cask "discord"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "homebrew/cask-versions/adoptopenjdk8"
cask "imageoptim"
cask "intellij-idea"
cask "iterm2"
cask "kap"
cask "keybase"
cask "mongodb-compass"
cask "neo4j"
cask "ngrok"
cask "qlmarkdown"
cask "qlstephen"
cask "robo-3t"
cask "sequel-pro"
cask "slack"
cask "sonos"
cask "spectacle"
cask "spotify"
cask "sublime-text"
cask "the-unarchiver"
cask "toggl-track"
cask "visual-studio-code"
cask "vlc"
cask "zoomus"

mas "Pixelmator Pro", id: 1289583905
mas "Amphetamine", id: 937984704
mas "Pocket", id: 568494494
mas "iA Writer", id: 775737590
